### ISSUE TITLE
`[E] socks5 tproxy udp addr` confusing log message

### ISSUE THREAD

**Issue by cattyhouse** [heiher/hev-socks5-tproxy#20]
when start hev-socks5-tproxy with this config:

```yml

socks5:
  port: 1080
  address: 127.0.0.1
  # Socks5 UDP relay mode (tcp|udp)
  udp: 'udp'
  # Socks5 server username
  #username: 'username'
  # Socks5 server password
  #password: 'password'
  # Socket mark
  #mark: 438

tcp:
  port: 1081
  address: '127.0.0.1'

udp:
  port: 1081
  address: '127.0.0.1'

# Redirect DNS to local server on gateway
#   [address]:port <-> [upstream]:53 (dnsmasq)
#dns:
  # DNS port
  #port: 1053
  # DNS address
  #address: '::'
  # DNS upstream
  #upstream: 127.0.0.1

misc:
#  task-stack-size: 8192 # task stack size (bytes)
#  connect-timeout: 5000 # connect timeout (ms)
#  read-write-timeout: 60000 # read-write timeout (ms)
#  log-file: stderr # stdout or file-path
  log-level: error # debug, info or warn or error
#  pid-file: /run/hev-socks5-tproxy.pid
  limit-nofile: 65535
```

upstream socks5 server is provided by pagefault's trojan-r client, everything works as expected. but hev-socks5-tproxy's log `[E] socks5 tproxy udp addr` is confusing, **why is this an [E] error log**?

by the way, i build hev-socks5-tproxy with this version: `6a85b48`

**Comment by heiher** [comment]
> it from here? does it indicate something went wrong?
> 
> https://github.com/heiher/hev-socks5-tproxy/blob/6a85b4858c8de3b9730384d8f983600d50853227/src/hev-socks5-tproxy.c#L139

This error message from the DNS part. I'll add a condition to skip trying to start the DNS task if it does not exist.

**Comment by heiher** [comment]
> another related question:
> 
> if change `udp: 'udp'` to `udp: 'tcp'`, **i know** this mode only works with hev-socks5-server, it does not work with trojan-r socks5 listening. when sending a udp packet like `dig @1.1.1.1 example.com` (udp packet), hev-socks5-tproxy just exit with `Segmentation fault`, i know it will fail, but that could be handled better with some error message instead of exit with seg fault. (side note, in this case trojan-r log shows: `socks: unsupported command 0x5`), just some thoughts, not a big issue if one knows how to configure the `udp: ` parameter.

Thanks. I'll fix it.

**Comment by heiher** [comment]
> > Thanks. I'll fix it.
> 
> i found another hev-socks5-tproxy `Segmentation fault` when **upstream socks5 server stopped/killed/quit/no longer listening**. can you reproduce this behavior on your side?
> 
> on : commit [11adf5e](https://github.com/heiher/hev-socks5-tproxy/commit/11adf5e0df02d1a67b1f5d5843ef4c5d8bd185b6)

No, I can't. I also cannot reproduce the above `cmd 0x5` unsupported crash.

**Comment by heiher** [comment]
> 2.5.2 release was fine, but producing tons of logs (20000+) in a short time

Have you bypass the socks5 server upstream outgoing connections to prevent them from going to tproxy again and getting stuck in an infinite loop?

**Comment by heiher** [comment]
Could you re-compile `hev-socks5-tproxy` by follow steps? and upload full logs and core dump file?

```shell
make clean
make CFLAGS="-g -O0" STRIP=true -j32
```

```yaml
misc:
  log-file: hs5t.log
  log-level: debug
```
